# Generated by Django 4.0 on 2021-12-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Pizza',
        ),
    ]
